-- Spring Boot (10 new: Q81-Q90)
INSERT INTO approved_questions (topic, text, answer, level, created_at, updated_at) VALUES
('spring-boot', 'Spring Boot 3.x - HTTP Interface Clients là gì?', 'HTTP Interface Clients là tính năng declarative HTTP clients tương tự Feign, sử dụng @HttpExchange, @GetExchange, @PostExchange annotations. Được implement bằng WebClient, giảm boilerplate code và type-safe hơn.', 'intermediate', datetime('now'), datetime('now')),
('spring-boot', 'Micrometer Observation API hoạt động như thế nào?', 'Observation API cung cấp unified observability (metrics + tracing + logging) qua single API. Hỗ trợ auto-instrumentation cho HTTP, JDBC, Kafka. Vendor-neutral approach cho phép switch giữa các monitoring systems.', 'advanced', datetime('now'), datetime('now')),
('spring-boot', '@ConditionalOnProperty dùng để làm gì?', '@ConditionalOnProperty enable/disable beans dựa trên properties. Dùng cho feature flags, environment-specific configurations, A/B testing. Ví dụ: @ConditionalOnProperty(name="feature.new-ui", havingValue="true")', 'intermediate', datetime('now'), datetime('now')),
('spring-boot', 'Cách troubleshoot Memory Leak trong Spring Boot?', 'Sử dụng heap dump analysis với Eclipse MAT. Common causes: unclosed resources, static collections, ThreadLocal leaks. Prevention: try-with-resources, WeakHashMap, proper ThreadLocal cleanup. Production debugging với jmap, jstat.', 'advanced', datetime('now'), datetime('now')),
('spring-boot', '@Retryable hoạt động như thế nào?', '@Retryable cung cấp declarative retry logic với Spring Retry. Hỗ trợ exponential backoff, @Recover cho fallback logic. Use cases: external API calls, database connection failures. Ví dụ: @Retryable(maxAttempts=3, backoff=@Backoff(delay=1000))', 'intermediate', datetime('now'), datetime('now')),
('spring-boot', 'Testcontainers trong Integration Testing?', 'Testcontainers sử dụng Docker containers cho tests. Cho phép test với real databases (PostgreSQL, MySQL, MongoDB). @DynamicPropertySource để configure connection. Tạo reproducible integration tests không phụ thuộc môi trường.', 'advanced', datetime('now'), datetime('now')),
('spring-boot', 'So sánh @Scheduled vs Quartz?', '@Scheduled: simple scheduling, cron expressions, single instance. Quartz: enterprise scheduler, clustering support, persistent jobs, distributed execution. Dùng @Scheduled cho simple tasks, Quartz cho complex enterprise scheduling.', 'intermediate', datetime('now'), datetime('now')),
('spring-boot', 'Custom Metrics với Micrometer?', 'Micrometer cung cấp Counter, Gauge, Timer, Distribution Summary. Tag-based metrics cho filtering. Export to Prometheus, Graphite, InfluxDB. Ví dụ: Counter.builder("api.calls").tag("endpoint", "/users").register(registry)', 'advanced', datetime('now'), datetime('now')),
('spring-boot', '@EventListener trong Event-Driven Architecture?', '@EventListener xử lý application events để decouple components. Sử dụng ApplicationEventPublisher để publish events. Hỗ trợ async processing với @Async. Tạo loose coupling giữa các modules.', 'intermediate', datetime('now'), datetime('now')),
('spring-boot', 'RestClient (Spring Boot 3.2+) khác gì RestTemplate?', 'RestClient là modern replacement cho RestTemplate. Fluent API, synchronous calls. Better error handling, simpler than WebClient. Migration path: RestTemplate → RestClient → WebClient (nếu cần async).', 'advanced', datetime('now'), datetime('now'));

-- Oracle (10 new: Q66-Q75)
INSERT INTO approved_questions (topic, text, answer, level, created_at, updated_at) VALUES
('oracle', 'Oracle 23c - JSON Relational Duality Views là gì?', 'JSON Relational Duality Views expose relational tables as JSON documents. Single source of truth (tables), có thể update via JSON hoặc SQL. ACID transactions on JSON. Use case: REST APIs với JSON payload nhưng vẫn giữ relational integrity.', 'advanced', datetime('now'), datetime('now')),
('oracle', 'Bind Variables vs Literals trong SQL Performance?', 'Bind variables: soft parse, reuse execution plan, prevent SQL injection. Literals: hard parse mỗi lần, library cache pollution. Bind variable peeking có thể gây suboptimal plans. Best practice: dùng bind variables cho OLTP.', 'intermediate', datetime('now'), datetime('now')),
('oracle', 'Oracle Sharding hoạt động như thế nào?', 'Sharding là horizontal partitioning across databases. System-managed (hash/range) hoặc user-defined sharding. Linear scalability, multi-tenant SaaS use cases. Sharding key quyết định data distribution.', 'advanced', datetime('now'), datetime('now')),
('oracle', 'Result Cache trong Oracle?', 'Result Cache lưu query và function results. Automatic invalidation khi data thay đổi. Shared across sessions. Monitor với V$RESULT_CACHE_STATISTICS. Use case: frequently accessed, rarely changed data.', 'intermediate', datetime('now'), datetime('now')),
('oracle', 'Blockchain Tables trong Oracle?', 'Blockchain Tables là immutable, append-only tables. Cryptographic hashing cho tamper-proof audit trail. Regulatory compliance use cases. Không thể UPDATE/DELETE rows sau retention period.', 'advanced', datetime('now'), datetime('now')),
('oracle', 'Phân tích Execution Plan?', 'TABLE ACCESS FULL: scan toàn bộ table. INDEX RANGE SCAN: dùng index. NESTED LOOPS: join nhỏ. HASH JOIN: join lớn. Cost và cardinality analysis. Dùng EXPLAIN PLAN hoặc DBMS_XPLAN.DISPLAY.', 'intermediate', datetime('now'), datetime('now')),
('oracle', 'PL/SQL Optimization - PRAGMA INLINE?', 'PRAGMA INLINE inline function calls để tăng performance. Compiler optimization levels (0-3). NOCOPY hint cho parameters (pass by reference). DETERMINISTIC và RESULT_CACHE cho function caching.', 'advanced', datetime('now'), datetime('now')),
('oracle', 'MERGE Statement - Upsert Operations?', 'MERGE combine INSERT và UPDATE trong single statement. Single pass through data, atomic operation. Use case: ETL, data synchronization. Syntax: MERGE INTO target USING source ON (condition) WHEN MATCHED THEN UPDATE WHEN NOT MATCHED THEN INSERT', 'intermediate', datetime('now'), datetime('now')),
('oracle', 'Advanced Queuing (AQ)?', 'AQ là built-in message queuing. ACID transactions, priority queuing, pub/sub. Event-driven architecture. Dùng DBMS_AQ package. Use case: async processing, decoupling systems.', 'advanced', datetime('now'), datetime('now')),
('oracle', 'WITH Clause (CTE)?', 'Common Table Expressions (CTE) với WITH clause. Recursive CTE cho hierarchical queries. Improved readability, query optimization. Ví dụ: WITH emp_hierarchy AS (SELECT ... UNION ALL SELECT ...) SELECT * FROM emp_hierarchy', 'intermediate', datetime('now'), datetime('now'));

-- AWS (10 new: Q56-Q65)
INSERT INTO approved_questions (topic, text, answer, level, created_at, updated_at) VALUES
('aws', 'Lambda SnapStart for Java?', 'SnapStart pre-initialize Lambda functions để giảm cold start. Up to 10x faster cold starts. Snapshot caching. Optimization cho Spring Boot on Lambda. Enable với snapStart: PublishedVersions trong function config.', 'advanced', datetime('now'), datetime('now')),
('aws', 'Parameter Store vs Secrets Manager?', 'Parameter Store: free tier, simple key-value. Secrets Manager: automatic rotation, cross-region replication, higher cost. Dùng Parameter Store cho configs, Secrets Manager cho credentials cần rotation.', 'intermediate', datetime('now'), datetime('now')),
('aws', 'Service Catalog là gì?', 'Service Catalog cung cấp pre-approved CloudFormation templates. Self-service infrastructure cho developers. Governance và compliance. Enterprise standardization. Admins control, users deploy.', 'advanced', datetime('now'), datetime('now')),
('aws', 'CloudWatch Logs Insights query language?', 'Query language cho log analysis. Filter, stats, parse operations. P99 latency analysis. Ví dụ: fields @timestamp, @message | filter @message like /ERROR/ | stats count() by bin(5m)', 'intermediate', datetime('now'), datetime('now')),
('aws', 'App Runner so với ECS/EKS/Lambda?', 'App Runner: simplified container deployment, auto-scaling, HTTPS. vs ECS: less control, easier. vs EKS: no Kubernetes complexity. vs Lambda: long-running containers. Use case: rapid prototyping, simple web apps.', 'advanced', datetime('now'), datetime('now')),
('aws', 'AWS Backup hoạt động như thế nào?', 'Centralized backup management cho EC2, RDS, DynamoDB, EFS. Cross-region, cross-account backups. Backup Vault Lock cho immutability. Compliance reporting. Automated backup policies.', 'intermediate', datetime('now'), datetime('now')),
('aws', 'Control Tower là gì?', 'Multi-account governance với landing zone automation. Guardrails (preventive và detective). Account Factory cho provisioning. Enterprise AWS adoption best practices.', 'advanced', datetime('now'), datetime('now')),
('aws', 'Global Accelerator vs CloudFront?', 'CloudFront: CDN, caching static content. Global Accelerator: TCP/UDP routing, static anycast IPs, no caching. CloudFront cho web content, Global Accelerator cho gaming, IoT, VoIP.', 'intermediate', datetime('now'), datetime('now')),
('aws', 'Graviton Processors?', 'ARM-based instances, 40% better price/performance vs x86. Software compatibility considerations (recompile needed). Migration testing requirements. Use case: cost optimization cho compute-intensive workloads.', 'advanced', datetime('now'), datetime('now')),
('aws', 'FinOps - Cost Allocation Tags?', 'Tag-based cost tracking cho chargeback. AWS Cost and Usage Reports. Budget alerts và anomaly detection. Best practice: tag resources với project, team, environment. Cost Explorer filtering.', 'advanced', datetime('now'), datetime('now'));

-- Angular (10 new: Q61-Q70)
INSERT INTO approved_questions (topic, text, answer, level, created_at, updated_at) VALUES
('angular', 'Angular 17+ Control Flow (@if, @for, @switch)?', 'Built-in syntax thay thế *ngIf, *ngFor, *ngSwitch. Better performance và type checking. Mandatory track in @for. @empty block support. Ví dụ: @if (user) { <div>{{user.name}}</div> } @else { <div>Loading...</div> }', 'advanced', datetime('now'), datetime('now')),
('angular', 'Signals effect() - Side Effects?', 'effect() run side effects khi signals change. Automatic dependency tracking. Cleanup on destroy. allowSignalWrites option. Use case: sync signal changes to localStorage, API calls.', 'advanced', datetime('now'), datetime('now')),
('angular', 'ViewChild vs ContentChild?', 'ViewChild: query own template. ContentChild: query projected content (<ng-content>). Lifecycle timing: ViewChild available in ngAfterViewInit, ContentChild in ngAfterContentInit. @ViewChildren và @ContentChildren cho multiple queries.', 'intermediate', datetime('now'), datetime('now')),
('angular', 'Virtual Scrolling với CDK?', 'Performance cho large lists (10,000+ items). DOM recycling, constant rendering time. cdk-virtual-scroll-viewport component. itemSize property. Use case: infinite scroll, large datasets.', 'advanced', datetime('now'), datetime('now')),
('angular', 'Router Lazy Loading với Preloading?', 'loadChildren syntax cho lazy loading. PreloadAllModules strategy preload sau initial load. Custom preloading strategies. Bundle size optimization. Ví dụ: { path: "admin", loadChildren: () => import("./admin/admin.module") }', 'intermediate', datetime('now'), datetime('now')),
('angular', 'Ivy Compilation Engine?', 'Next-gen compilation và rendering. Smaller bundles, faster compilation. Locality principle (compile components independently). Foundation cho Signals, Standalone Components. Tree-shaking improvements.', 'advanced', datetime('now'), datetime('now')),
('angular', 'FormArray Dynamic Forms?', 'Manage array of form controls. Add/remove controls dynamically. Use cases: multiple addresses, skill sets. FormBuilder integration. Ví dụ: this.fb.array([this.fb.control("")]) với push/removeAt methods.', 'intermediate', datetime('now'), datetime('now')),
('angular', 'Zone.js và Zoneless Future?', 'Zone.js: monkey-patching async APIs cho change detection. Performance overhead. Zoneless Angular với Signals: manual change detection. provideExperimentalZonelessChangeDetection(). Future: Signals-based reactivity.', 'advanced', datetime('now'), datetime('now')),
('angular', 'Material Theming?', 'Pre-built themes (indigo-pink, deeppurple-amber). Custom themes với mat.define-palette. Dark mode support. CSS variables cho runtime switching. SCSS theming API. Ví dụ: @include mat.all-component-themes($theme)', 'intermediate', datetime('now'), datetime('now')),
('angular', 'Micro-frontends với Module Federation?', 'Webpack 5 Module Federation cho micro-frontends. Host và remote apps. Independent deployment. Shared dependencies. State management across apps. Use case: large enterprise apps, team autonomy.', 'advanced', datetime('now'), datetime('now'));
